### ISSUE TITLE
Graphic card runs out of memory

### ISSUE THREAD

**Issue by davizinho5** [karlpauwels/simtrack#8]
Hello, 

First of all, I wrote on Friday in a closed issue, and then I thought this was a really bad idea, so I decided to open a new issue but the message has the same content.

I have a similar problem as mklingen had (https://github.com/karlpauwels/simtrack/issues/4), the device runs out of memory most of the times (95%) I launch it, but in this case with an ASUS camera. I thought it was because I use an old graphic card, still is Fermi class , so I though it would be enough. Here is my nvidia-smi:

![smi-nvidia](https://cloud.githubusercontent.com/assets/8976895/12546535/cd7e811a-c34a-11e5-932f-82e229174824.png)

I think it should have enough memory for both tracking and detection, but anyways, is there a way to use less memory? What if I use a 3D model with less points on it?
Also, in my case I would only need the tracking system since I can provide a different detection procedure. Is there a simple way to launch only the tracking and sharing the detection info from another node?

Thanks!

**Comment by karlpauwels** [comment]
For the Xtion you'll need about 300MB for tracking and 1GB for detection with the three example objects. You seem to only have about 1GB free since your desktop also uses up memory. You can try it with one object by commenting [here](https://github.com/karlpauwels/simtrack/blob/master/simtrack_nodes/config/demo_objects.yaml).

For most models, the model size for detection depends more on the specific type of texture (the number of keypoints that can be extracted) and the resolution of the texture, than on the number of 3D points in the model. Unless of course your model geometry is huge. 

The easiest way to use a custom detection procedure is to have a look at the [detectorThreadFunction](https://github.com/karlpauwels/simtrack/blob/master/simtrack_nodes/src/multi_rigid_node.cpp#L55) and replace `multi_rigid_detector_` with your own object.

Hope this helps!
